name: docker-image

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build footstone
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Build yavirt
        uses: docker/build-push-action@v2
        with:
          context: "./yavirt-prebuild"
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:yavirt-prebuild
